name: "vipm-UninstallPackage"
author: "NEVSTOP"
description: "CICD Action to uninstall VIPM package"
branding:
  icon: "anchor"
  color: "green"

inputs:
  LabVIEW_Version:
    description: "LabVIEW Version Used"
    required: false
    default: "2017"
  Architecture:
    description: "32bit/64bit Version of LabVIEW Used"
    required: false
    default: "x86"
  Package:
    description: "Package could be PackageName/PacakgeWithVersion"
    required: true
    default: ""

runs:
  using: "composite"

  steps:
    - id: build-vip
      uses: LV-APT/lvCICD@main
      with:
        LabVIEW_Version: ${{ inputs.LabVIEW_Version }}
        Architecture: ${{ inputs.Architecture }}
        Operation: vipm_unInstallPackages
        Parameter1: ${{ inputs.Package }}

